/* Uraga Atlas — dashboard logic.
 *
 * Our own data (species index, AI field notes, traits, occurrence clusters)
 * is served as static JSON from ./data. Photographs and individual occurrence
 * records are NOT baked in — they are fetched live:
 *   photographs        iNaturalist  /v1/taxa/{inatTaxonId}
 *   occurrence points  GBIF         /v1/occurrence/search?taxonKey=…
 * Both send Access-Control-Allow-Origin:*, so the browser can call them
 * directly with no key and no proxy.
 */
/* The map is Leaflet over a near-monochrome slippy basemap: the red occurrence
 * points and amber clusters have to stay the loudest thing on screen.
 *
 * Basemap tiles are KEY-FREE providers. (CARTO's Positron/Voyager/Dark Matter
 * were dropped in 2026-08 — CARTO now watermarks unauthenticated raster tiles
 * with "API KEY REQUIRED".) The pale-grey and dark styles are Esri's Light/Dark
 * Gray Canvas, which ship label-free base tiles plus a separate reference
 * (labels) layer — hence the optional `labels` URL, drawn just above the base.
 *
 * P is now only the atlas extent, used to scope the GBIF query and to frame
 * the initial view. Projection is Leaflet's (Web Mercator), not ours. */
const P = {minLon:60, maxLon:98, minLat:4, maxLat:38};
const ESRI = 'https://server.arcgisonline.com/ArcGIS/rest/services';
const BASEMAPS = {
  positron: {
    url: `${ESRI}/Canvas/World_Light_Gray_Base/MapServer/tile/{z}/{y}/{x}`,
    labels: `${ESRI}/Canvas/World_Light_Gray_Reference/MapServer/tile/{z}/{y}/{x}`,
    attr: 'Tiles &copy; Esri &mdash; Esri, HERE, Garmin, &copy; OpenStreetMap contributors', max: 16, dark: false},
  voyager: {
    url: 'https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',
    attr: '&copy; OpenStreetMap contributors', max: 19, dark: false},
  darkmatter: {
    url: `${ESRI}/Canvas/World_Dark_Gray_Base/MapServer/tile/{z}/{y}/{x}`,
    labels: `${ESRI}/Canvas/World_Dark_Gray_Reference/MapServer/tile/{z}/{y}/{x}`,
    attr: 'Tiles &copy; Esri &mdash; Esri, HERE, Garmin', max: 16, dark: true},
  imagery: {
    url: `${ESRI}/World_Imagery/MapServer/tile/{z}/{y}/{x}`,
    attr: 'Imagery &copy; Esri, Maxar, Earthstar Geographics', max: 18, dark: true},
  topo: {
    url: 'https://{s}.tile.opentopomap.org/{z}/{x}/{y}.png',
    attr: '&copy; OpenStreetMap contributors, SRTM &copy; OpenTopoMap (CC-BY-SA)',
    max: 17, dark: false},
};

const API = {
  inat: id => `https://api.inaturalist.org/v1/taxa/${id}`,
  // OBIS holds marine occurrences GBIF under-covers (sea turtles, sea snakes).
  // The WKT polygon MUST be encoded — unencoded spaces silently break the URL,
  // which is what made an earlier attempt look like OBIS had no data at all.
  // NCBI deep links — data is public domain; we precompute the counts and link
  // out to the live database rather than fetching at record time
  ncbiSeq: name => `https://www.ncbi.nlm.nih.gov/nuccore/?term=${encodeURIComponent(name + '[Organism]')}`,
  ncbiTax: name => `https://www.ncbi.nlm.nih.gov/Taxonomy/Browser/wwwtax.cgi?name=${encodeURIComponent(name)}`,
  ncbiGenome: name => `https://www.ncbi.nlm.nih.gov/assembly/?term=${encodeURIComponent(name + '[Organism]')}`,
  obis: name => 'https://api.obis.org/v3/occurrence?' + new URLSearchParams({
    scientificname: name, size: 500,
    geometry: `POLYGON((${P.minLon} ${P.minLat},${P.maxLon} ${P.minLat},` +
              `${P.maxLon} ${P.maxLat},${P.minLon} ${P.maxLat},${P.minLon} ${P.minLat}))`,
  }),
  gbif: (key, limit) =>
    `https://api.gbif.org/v1/occurrence/search?taxonKey=${key}` +
    `&hasCoordinate=true&hasGeospatialIssue=false` +
    // scope to the atlas extent — an unbounded query returns the species'
    // whole world range (Calotes versicolor: 24,520 global vs 12,696 here)
    `&decimalLatitude=${P.minLat - 1},${P.maxLat + 1}` +
    `&decimalLongitude=${P.minLon - 2},${P.maxLon + 2}` +
    `&limit=${limit}`,
};
const POINT_LIMIT = 300;
// Our own JSON is regenerated by the build scripts; force revalidation so a
// rebuilt data/ is never masked by a stale cached copy (this bit twice).
const DATA_FETCH = {cache: 'no-cache'};

const $ = s => document.querySelector(s);
const fmt = n => (n ?? 0).toLocaleString('en-IN');
// Deep link to a species. Absolute so links printed into a PDF resolve, and
// used both by the report and by shareable ?sp= URLs.
const speciesURL = id => `${location.origin}${location.pathname}?sp=${id}`;
const spLink = (id, inner) =>
  `<a class="splink" href="${speciesURL(id)}" target="_blank" rel="noopener">${inner}</a>`;
function setSpeciesURL(id){
  history.replaceState(null, '', id ? `?sp=${id}` : location.pathname);
}
const IUC = {LC:'--lc', NT:'--nt', VU:'--vu', EN:'--en', CR:'--cr', DD:'--dd'};
const IUNAME = {LC:'Least Concern', NT:'Near Threatened', VU:'Vulnerable',
                EN:'Endangered', CR:'Critically Endangered', DD:'Data Deficient'};
const AILAB = {description:'Description', identificationRemarks:'Identification',
  habitat:'Habitat', behavior:'Behaviour', reproductionNotes:'Reproduction',
  distributionRemarks:'Distribution', callDescription:'Call'};
/* mirrors _segFields in the app's detail.dart */
const SEGS = [
  ['Overview',  ['description','identificationRemarks']],
  ['Ecology',   ['habitat','distributionRemarks']],
  ['Behaviour', ['behavior','reproductionNotes','callDescription']],
];
const md = t => t.replace(/\*\*(.+?)\*\*/g,'<b>$1</b>').replace(/[*_](.+?)[*_]/g,'<em>$1</em>');

let DATA = null, INDEX = [], detailCache = new Map(), liveCache = new Map();
let picked = null, detail = null, live = null, seg = 0, full = false;
const state = {grp:new Set(), iucn:new Set(), q:'', z:0, base:'positron',
               view:'heat', nav:'list', breaks:null};
// set by report.js when an administrative region is selected
let region = null, regionIds = null;
// degrees spanned by the cells currently drawn (corpus level, or a selected
// region's adaptive display size); drawHeatCells/drawBubbles size to it
let viewCell = 0.55;
const rangeCache = new Map();

/* ── the map ──────────────────────────────────────────── */
const map = L.map('map', {
  zoomControl: false,            // we render our own, positioned around the dock
  attributionControl: false,     // ditto, so it can dodge the panels
  minZoom: 3, maxZoom: 17,
  worldCopyJump: true,
}).fitBounds([[P.minLat, P.minLon], [P.maxLat, P.maxLon]]);

// India's official boundary (full claimed extent — J&K and Arunachal included),
// drawn over the basemap so the country outline is unambiguous whichever tile
// provider is active. Added before the data layers so it sits beneath points.
const indiaLayer   = L.layerGroup().addTo(map);
function drawIndia(gj){
  indiaLayer.clearLayers();
  L.geoJSON(gj, { interactive: false, className: 'india-outline', fill: false }).addTo(indiaLayer);
}

const clusterLayer = L.layerGroup().addTo(map);
const pointLayer   = L.layerGroup().addTo(map);
// featureGroup, not layerGroup: only featureGroup exposes getBounds(), which
// is what frames a selected region
const regionLayer  = L.featureGroup().addTo(map);
// IUCN range polygons sit under the points: 209 of 1,096 species have no
// georeferenced records at all, and for those the range is the only map there is
const rangeLayer   = L.layerGroup().addTo(map);
let tileLayer = null, labelLayer = null;

function setBasemap(key){
  const b = BASEMAPS[key] || BASEMAPS.positron;
  state.base = key;
  if (tileLayer) map.removeLayer(tileLayer);
  if (labelLayer){ map.removeLayer(labelLayer); labelLayer = null; }
  const opts = { maxZoom: 19, maxNativeZoom: b.max };
  if (b.url.includes('{s}')) opts.subdomains = 'abc';
  tileLayer = L.tileLayer(b.url, { ...opts, attribution: b.attr }).addTo(map);
  tileLayer.setZIndex(0);
  if (b.labels){                              // Esri gray canvas: labels are a separate layer
    labelLayer = L.tileLayer(b.labels, opts).addTo(map);
    labelLayer.setZIndex(1);
  }
  document.body.classList.toggle('basedark', b.dark);
  $('#attrib').innerHTML = b.attr + ' &middot; occurrences GBIF &middot; status IUCN';
}

/* Clusters are precomputed at four grid resolutions. Pick whichever leaves the
 * cell centres far enough apart to read at the current zoom: Leaflet's world is
 * 256·2^z px across 360°, so spacing in px = cellDegrees · 256·2^z / 360.
 * Below ~45px the bubbles start merging into one another. */
const CELLS_FALLBACK = {z0:4.4, z1:2.2, z2:1.1, z3:0.5};
const LEVEL_KEYS = ['z0', 'z1', 'z2', 'z3'];
const pxPerDeg = z => 256 * Math.pow(2, z) / 360;
const cellDeg = lv => ((DATA && DATA.cells) || CELLS_FALLBACK)[LEVEL_KEYS[lv]];

/* Bubbles must be big enough to hold a number; heatmap cells only have to be
   visible. So the heatmap can run a much finer grid at the same zoom — which
   is most of why it resolves more detail than the bubbles ever did. */
const FLOOR = {heat: 9, clusters: 45};

function levelFor(z, view = state.view){
  // the finest grid whose spacing still clears the readability floor
  for (let i = LEVEL_KEYS.length - 1; i >= 0; i--){
    if (cellDeg(i) * pxPerDeg(z) >= FLOOR[view]) return i;
  }
  return 0;
}

/* Pale straw → amber → burnt sienna. Sequential, single family, and
   deliberately clear of the red (--occ) that marks occurrence points. */
const HEAT = ['#FEF0C0', '#FCD97E', '#F8BE3C', '#F59E0B', '#D97706', '#9A3412'];

/** Class breaks by quantile, not equal interval. Cell counts are savagely
 *  skewed — at 2.2° the median cell holds ~107 records and the largest 8,438 —
 *  so equal intervals would paint one hot cell above a uniform floor.
 *  Returns the inclusive upper bound of each class. */
function heatBreaks(values){
  const v = values.filter(n => n > 0).sort((a, b) => a - b);
  if (!v.length) return [];
  const out = [];
  for (let i = 1; i <= HEAT.length; i++){
    const q = v[Math.min(v.length - 1, Math.floor(v.length * i / HEAT.length))];
    // drop duplicate bounds, or a long tail of 1s swallows several classes
    if (!out.length || q > out[out.length - 1]) out.push(q);
  }
  out[out.length - 1] = v[v.length - 1];
  return out;
}
/** Darkest classes always win the top of the ramp, however many survive. */
function heatColour(n, breaks){
  const i = breaks.findIndex(b => n <= b);
  const cls = i < 0 ? breaks.length - 1 : i;
  return HEAT[HEAT.length - breaks.length + cls];
}

/** Bubble radius, bounded by the room the grid actually leaves at this zoom.
 *  Area-proportional would be honest but unreadable across a 1–25,000 range,
 *  so this is sqrt-scaled against the largest cell currently drawn; the label
 *  carries the exact number. */
function clusterRadius(n, nmax, zoom, cellDegrees){
  const spacing = cellDegrees * pxPerDeg(zoom);
  const maxR = Math.max(12, Math.min(27, spacing * 0.46));
  const minR = Math.min(9.5, maxR * 0.6);
  return minR + (maxR - minR) * Math.sqrt(n / Math.max(nmax, 1));
}

/* ── boot ─────────────────────────────────────────────── */
(async function init(){
  try {
    // basemap.json is no longer fetched — the coastline comes from the tiles
    const [clusters, index, india] = await Promise.all([
      fetch('data/clusters.json', DATA_FETCH).then(r => r.json()),
      fetch('data/index.json', DATA_FETCH).then(r => r.json()),
      fetch('data/india.geojson', DATA_FETCH).then(r => r.json()).catch(() => null),
    ]);
    DATA = clusters; INDEX = index;
    setBasemap(state.base);
    if (india) drawIndia(india);
    state.z = levelFor(map.getZoom());
    render();
    initRegionPanel();            // report.js — loads its own index
    // ?sp=<id> opens that species directly (shared links, report hyperlinks)
    const spId = new URLSearchParams(location.search).get('sp');
    if (spId){
      const sp = INDEX.find(s => String(s.id) === spId);
      if (sp){ selectSpecies(sp); full = true; $('#dock').classList.add('full'); }
    }
  } catch (e) {
    $('#boot').innerHTML =
      `<p>Could not load the dataset.</p><p class="dim">${e.message}</p>`;
    return;
  }
  $('#boot').remove();
})();

/* ── filtering ────────────────────────────────────────── */
function matches(sp){
  if (regionIds && !regionIds.has(sp.id)) return false;
  if (state.grp.size && !state.grp.has(sp.grp)) return false;
  if (state.iucn.size && !state.iucn.has(sp.iucn)) return false;
  if (state.q){
    const q = state.q.toLowerCase();
    if (!(sp.sci.toLowerCase().includes(q) || (sp.com || '').toLowerCase().includes(q) ||
          (sp.fam || '').toLowerCase().includes(q))) return false;
  }
  return true;
}
function keep(key){
  const [g, i] = key.split('|');
  if (state.grp.size && !state.grp.has(g)) return false;
  if (state.iucn.size && !state.iucn.has(i)) return false;
  return true;
}

/* ── left panel ───────────────────────────────────────── */
function opt(label, count, on, onClick, color){
  const b = document.createElement('button');
  b.className = 'opt' + (color ? ' swatched' : '');
  b.setAttribute('aria-pressed', on);
  if (color) b.style.setProperty('--c', color);
  b.innerHTML = `<span class="box"></span>${color ? '<span class="sw"></span>' : ''}
    <span>${label}</span><span class="n">${fmt(count)}</span>`;
  b.onclick = onClick;
  return b;
}
/* buildPanel() recreates these elements on every render — selecting a species,
   expanding a tree node, changing a filter — so a collapsed section reopened
   itself every time. Open state is remembered per title and reapplied. */
const accOpen = {};

function accordion(title, chosen, children, open){
  const d = document.createElement('details');
  d.className = 'acc';
  d.open = title in accOpen ? accOpen[title] : open;
  d.addEventListener('toggle', () => { accOpen[title] = d.open; });
  d.innerHTML = `<summary class="acch"><span class="car">›</span>${title}
    <span class="cnt">${chosen || 'All'}</span></summary>`;
  const body = document.createElement('div');
  body.className = 'accb';
  children.forEach(c => body.appendChild(c));
  d.appendChild(body);
  return d;
}
function toggle(set, k){ set.has(k) ? set.delete(k) : set.add(k); render(); }

function buildPanel(){
  const b = $('#pbody'); b.innerHTML = '';

  b.appendChild(accordion('Taxonomic group',
    state.grp.size ? `${state.grp.size} selected` : '',
    DATA.facets.grp.map(g => opt(g.k, g.n, state.grp.has(g.k), () => toggle(state.grp, g.k))),
    false));
  b.appendChild(accordion('Conservation status',
    state.iucn.size ? `${state.iucn.size} selected` : '',
    DATA.facets.iucn.map(s => opt(s.label, s.n, state.iucn.has(s.k),
      () => toggle(state.iucn, s.k), `var(${IUC[s.k]})`)),
    false));

  const list = INDEX.filter(matches);
  const h = document.createElement('div');
  h.className = 'acch spechead'; h.style.cursor = 'default';
  h.innerHTML = `<span style="color:var(--accent)">◆</span>Species
    <span class="cnt">${fmt(list.length)}</span>`;
  const nav = document.createElement('span');
  nav.className = 'navtog';
  [['list','List'], ['tree','Tree']].forEach(([k, label]) => {
    const t = document.createElement('button');
    t.textContent = label;
    t.setAttribute('aria-pressed', state.nav === k);
    t.onclick = () => { state.nav = k; render(); };
    nav.appendChild(t);
  });
  h.appendChild(nav);
  b.appendChild(h);

  if (state.nav === 'tree'){
    b.appendChild(buildTree(list));
    return;
  }

  const sl = document.createElement('div');
  sl.className = 'splist';
  if (!list.length){
    sl.innerHTML = '<div class="hollow">No species match these filters.</div>';
  } else {
    // the full list is 1,096 rows — render a window and grow it on scroll
    const slice = list.slice(0, state.shown || 60);
    slice.forEach(sp => sl.appendChild(speciesRow(sp)));
    if (list.length > slice.length){
      const more = document.createElement('button');
      more.className = 'more';
      more.textContent = `Show more — ${fmt(list.length - slice.length)} remaining`;
      more.onclick = () => { state.shown = (state.shown || 60) + 120; render(); };
      sl.appendChild(more);
    }
  }
  b.appendChild(sl);
}


/* ── taxonomic tree ───────────────────────────────────────
 * A second way to navigate the same filtered set, not a second filter: the
 * cluster grid is keyed only by group|status, so a clade cannot be applied to
 * the map exactly, and pretending otherwise would misreport the corpus.
 *
 * Ranks come from index.json `lin`: class, order, suborder, family,
 * subfamily, genus. Suborder and subfamily are genuinely unknown for many
 * species (501 and 395 of 1,096), and an empty rank is SKIPPED rather than
 * rendered as "Unknown" — the child simply attaches to the nearest known
 * ancestor, which is how the app's tree behaves.
 */
const RANKS = ['Class', 'Order', 'Suborder', 'Family', 'Subfamily', 'Genus'];
const openNodes = new Set(['REPTILIA', 'AMPHIBIA']);

function buildTree(list){
  const wrap = document.createElement('div');
  wrap.className = 'tree';
  if (!list.length){
    wrap.innerHTML = '<div class="hollow">No species match these filters.</div>';
    return wrap;
  }
  if (!list[0].lin){
    wrap.innerHTML = '<div class="hollow">This build of the data has no lineage —'
      + ' rerun tools/build_dashboard.py.</div>';
    return wrap;
  }

  // nest species under their non-empty ranks
  const root = {kids:new Map(), n:0};
  list.forEach(sp => {
    let node = root;
    node.n++;
    (sp.lin || []).forEach((name, depth) => {
      if (!name) return;                       // rank unknown: collapse it away
      if (!node.kids.has(name))
        node.kids.set(name, {kids:new Map(), n:0, rank:RANKS[depth], name});
      node = node.kids.get(name);
      node.n++;
    });
    (node.species || (node.species = [])).push(sp);
  });

  // Nested containers (a branch = its header row + a `.tchildren` box) so the
  // connector lines are pure CSS: `.tchildren` carries the vertical guide as a
  // left border, and each child a short horizontal tick. Indentation comes from
  // the nesting, not inline padding.
  const makeNode = (node, path) => {
    const open = openNodes.has(path);
    const branch = document.createElement('div');
    branch.className = 'tbranch';
    const row = document.createElement('button');
    row.className = 'tnode';
    row.setAttribute('aria-expanded', open);
    row.innerHTML = `<span class="tcar">${open ? '⌄' : '›'}</span>
      <span class="tname">${node.name}</span>
      <span class="trank">${node.rank}</span>
      <span class="tn">${fmt(node.n)}</span>`;
    row.onclick = () => {
      open ? openNodes.delete(path) : openNodes.add(path);
      render();
    };
    branch.appendChild(row);
    if (open){
      const kids = document.createElement('div');
      kids.className = 'tchildren';
      [...node.kids.values()]
        .sort((a, b) => a.name.localeCompare(b.name))
        .forEach(k => kids.appendChild(makeNode(k, path + '/' + k.name)));
      (node.species || []).sort((a, b) => a.sci.localeCompare(b.sci)).forEach(sp => {
        const r = speciesRow(sp);
        r.classList.add('tleaf');
        kids.appendChild(r);
      });
      branch.appendChild(kids);
    }
    return branch;
  };
  [...root.kids.values()]
    .sort((a, b) => a.name.localeCompare(b.name))
    .forEach(k => wrap.appendChild(makeNode(k, k.name)));
  return wrap;
}

function speciesRow(sp){
  const r = document.createElement('button');
  r.className = 'sprow';
  r.style.setProperty('--c', `var(${IUC[sp.iucn]})`);
  r.setAttribute('aria-current', picked && picked.id === sp.id);
  r.innerHTML = `<span class="ph" data-ph="${sp.id}"></span>
    <span style="flex:1;min-width:0">
      <span class="nm">${sp.sci}</span>
      <span class="cm">${sp.com || '—'}</span>
    </span>
    <span style="display:flex;flex-direction:column;align-items:flex-end;gap:3px">
      <span class="sd"></span><span class="rc">${fmt(sp.n)}</span>
    </span>`;
  r.onclick = () => selectSpecies(sp);
  return r;
}

/* ── selection: fetch record + photos + points ────────── */
async function selectSpecies(sp){
  if (picked && picked.id === sp.id){
    picked = detail = live = null; full = false;
    $('#dock').classList.remove('full');
    setSpeciesURL(null);
    return render();
  }
  picked = sp; detail = null; live = null; state.shown = state.shown || 60;
  setSpeciesURL(sp.id);
  render();                                  // paint the selected state immediately

  // our own record — static JSON
  if (!detailCache.has(sp.id)){
    try {
      detailCache.set(sp.id, await fetch(`data/species/${sp.id}.json`, DATA_FETCH).then(r => r.json()));
    } catch { detailCache.set(sp.id, null); }
  }
  detail = detailCache.get(sp.id);
  const f = SEGS.findIndex(([, ks]) => detail && ks.some(k => detail.ai[k]));
  seg = f < 0 ? 0 : f;
  if (picked && picked.id === sp.id) render();

  // photographs + occurrence points — live APIs, a few seconds each
  const cached = liveCache.has(sp.id);
  if (!cached){
    liveCache.set(sp.id, fetchLive(sp));
    setBusy(true, 'Fetching photographs and occurrence records…');
  }
  let got;
  try { got = await liveCache.get(sp.id); }
  finally { if (!cached) setBusy(false); }
  // never keep a partial failure: one rate-limited request would otherwise
  // leave this species permanently empty for the rest of the session
  if (got && got.errors.some(e => !e.includes('no '))) liveCache.delete(sp.id);
  if (picked && picked.id === sp.id){
    live = got;
    fitToPoints(got.points);     // frame the species' whole known range
    render();
  }
  drawRange(sp);
}

/** The IUCN range polygon, drawn beneath the occurrence points. For the 209
 *  species with no georeferenced records this is the entire map, so it is
 *  fetched even when points come back empty. */
async function drawRange(sp){
  rangeLayer.clearLayers();
  if (!sp || !sp.rng) return;
  let gj = rangeCache.get(sp.id);
  if (gj === undefined){
    try { gj = await fetch(`data/ranges/${sp.id}.geojson`, DATA_FETCH).then(r => r.json()); }
    catch { gj = null; }
    rangeCache.set(sp.id, gj);
  }
  if (!gj || !picked || picked.id !== sp.id) return;
  const layer = L.geoJSON(gj, {
    style: {color:'#2F855A', weight:1.1, opacity:.85,
            fillColor:'#38A169', fillOpacity:.20},
    interactive: false,
  }).addTo(rangeLayer);
  rangeLayer.eachLayer(l => l.bringToBack && l.bringToBack());
  // with no points to frame, the range is what the camera should show
  if (live && !live.points.length) fitBounds(layer.getBounds());
}

/** Fetch with a bounded retry. A single transient failure used to be cached
 *  forever (the promise, errors and all), so one rate-limited request left a
 *  species stuck on "occurrence points unavailable" until a full reload —
 *  which is what made it look as though many species had no data at all. */
async function getJSON(url, tries = 3){
  let wait = 400;
  for (let i = 0; i < tries; i++){
    try {
      const r = await fetch(url);
      if (r.ok) return r.json();
      // 429 and 5xx are worth retrying; a 404 never will be
      if (r.status !== 429 && r.status < 500) throw new Error('HTTP ' + r.status);
    } catch (e){
      if (i === tries - 1) throw e;
    }
    await new Promise(res => setTimeout(res, wait));
    wait *= 2;
  }
  throw new Error('unavailable');
}

async function fetchLive(sp){
  const out = {photos: [], points: [], errors: [], obis: 0};
  const jobs = [];

  if (sp.inat){
    jobs.push(getJSON(API.inat(sp.inat)).then(j => {
      const t = (j.results || [])[0] || {};
      out.photos = (t.taxon_photos || []).slice(0, 6).map(tp => ({
        url: tp.photo.medium_url || tp.photo.url,
        credit: tp.photo.attribution || '',
        licence: tp.photo.license_code || '',
      }));
      if (!out.photos.length && t.default_photo){
        out.photos = [{url: t.default_photo.medium_url, credit: t.default_photo.attribution || '',
                       licence: t.default_photo.license_code || ''}];
      }
    }).catch(() => out.errors.push('photographs')));
  } else out.errors.push('photographs (no iNaturalist id)');

  if (sp.gbif){
    jobs.push(getJSON(API.gbif(sp.gbif, POINT_LIMIT)).then(j => {
      out.total = j.count;
      out.points = (j.results || [])
        .filter(r => r.decimalLatitude != null && r.decimalLongitude != null)
        .map(r => ({
          lat: r.decimalLatitude, lon: r.decimalLongitude,
          date: (r.eventDate || '').slice(0, 10),
          basis: r.basisOfRecord || '', who: r.recordedBy || '',
          ds: r.datasetName || '', country: r.country || '',
          unc: r.coordinateUncertaintyInMeters, key: r.key,
          oid: r.occurrenceID || '', src: 'GBIF',
        }));
    }).catch(() => out.errors.push('occurrence points')));
  } else out.errors.push('occurrence points (no GBIF key)');

  // Marine species only. OBIS holds sea turtle and sea snake records GBIF
  // under-covers — Chelonia mydas: 573 in GBIF against 1,313 in OBIS for this
  // box — but it is behind for others, so it is merged, never substituted.
  if (sp.mar){
    jobs.push(getJSON(API.obis(sp.sci)).then(j => {
      out.obisRaw = (j.results || [])
        .filter(r => r.decimalLatitude != null && r.decimalLongitude != null)
        .map(r => ({
          lat: r.decimalLatitude, lon: r.decimalLongitude,
          date: (r.eventDate || '').slice(0, 10),
          basis: r.basisOfRecord || '', who: r.recordedBy || '',
          ds: r.dataset_id || '', country: r.country || '',
          unc: r.coordinateUncertaintyInMeters, key: r.id,
          oid: r.occurrenceID || '', src: 'OBIS',
        }));
    }).catch(() => out.errors.push('marine records (OBIS)')));
  }

  await Promise.all(jobs);

  // Merge OBIS in, de-duplicated: the two aggregate some of the same
  // satellite-tracking datasets, so a shared occurrenceID — or failing that a
  // matching position and date — is one observation counted twice.
  if (out.obisRaw && out.obisRaw.length){
    const key = p => p.oid || `${p.lat.toFixed(3)},${p.lon.toFixed(3)},${p.date}`;
    const seen = new Set(out.points.map(key));
    for (const p of out.obisRaw){
      const k = key(p);
      if (seen.has(k)) continue;
      seen.add(k);
      out.points.push(p);
      out.obis++;
    }
    // deliberately NOT added to out.total: GBIF's count is its full match
    // count, while out.obis counts only the records new within the page we
    // actually fetched. Summing them would mix a total with a sample.
  }
  delete out.obisRaw;
  return out;
}

/* ── map ──────────────────────────────────────────────── */

/** The grid to draw: the corpus level, or — when a region is selected — that
 *  region's OWN grid, so the map is genuinely scoped to the selection instead
 *  of showing the whole corpus behind an outline.
 *
 *  Region grids are stored at the finest cell size, and every coarser level is
 *  a power-of-two multiple of it, so aggregating up is exact: no point moves
 *  cell and no count is estimated. Cells stay keyed group|status, so the
 *  taxonomic-group and status filters remain exact inside a region too.
 */
function cellsForView(){
  if (!region || !region.cells){
    viewCell = cellDeg(state.z);
    return DATA.levels[LEVEL_KEYS[state.z]];
  }
  // A selected region carries its own grid at an adaptive fine base. Pick the
  // display cell from the ACTUAL zoom so zooming in re-grids finer (down to the
  // stored base), instead of being pinned at the corpus 0.55°.
  const want = 26 / pxPerDeg(map.getZoom());        // aim for ~26px cells
  const factor = Math.max(1, Math.round(want / region.cell));
  viewCell = region.cell * factor;
  const acc = new Map();
  for (const c of region.cells){
    const kx = Math.floor(c.k[0] / factor), ky = Math.floor(c.k[1] / factor);
    const id = kx + ',' + ky;
    let e = acc.get(id);
    if (!e){ e = {x: (kx + 0.5) * viewCell, y: (ky + 0.5) * viewCell, b: {}}; acc.set(id, e); }
    for (const k in c.b) e.b[k] = (e.b[k] || 0) + c.b[k];
  }
  return [...acc.values()];
}

function drawMap(){
  // The corpus grid is hidden while an AOI is being drawn/queried AND while an
  // AOI is applied: a custom area is defined by its outline, and the corpus grid
  // would show its species' records across ALL of India, not inside the boundary.
  if (window.__aoiDrawing || (region && region.aoi)){
    pointLayer.clearLayers(); clusterLayer.clearLayers();
    if (region && region.aoi && !window.__aoiDrawing){
      $('#r-occ').textContent = fmt(region.nrec);
      $('#r-cl').textContent = '—';
      $('#r-sp').textContent = fmt(region.sp.length);
      $('#foot').textContent = `${region.name} · ${fmt(region.sp.length)} species`;
      drawDock(region.nrec, 0);
    }
    return;
  }
  if (!picked) rangeLayer.clearLayers();
  // regionLayer is owned by drawRegion() and must NOT be cleared here: the
  // zoomend path calls drawMap() on its own, which would wipe the outline of
  // the selected region every time the map zoomed.
  if (picked) return drawSpeciesMap();
  pointLayer.clearLayers();
  clusterLayer.clearLayers();

  const cells = cellsForView();
  const zoom = map.getZoom();
  // count each cell once: radii and class breaks both need the whole set
  const counts = cells.map(c => {
    let n = 0;
    for (const k in c.b) if (keep(k)) n += c.b[k];
    return n;
  });

  const total = counts.reduce((a, b) => a + b, 0);
  const shown = counts.filter(n => n).length;
  state.breaks = state.view === 'heat' ? heatBreaks(counts) : null;

  if (state.view === 'heat') drawHeatCells(cells, counts);
  else drawBubbles(cells, counts, zoom);

  $('#r-occ').textContent = fmt(total);
  $('#r-cl').textContent = fmt(shown);
  $('#r-sp').textContent = fmt(INDEX.filter(matches).length);
  $('#foot').textContent = region
    ? `${region.name} · ${fmt(region.sp.length)} species`
    : `${fmt(DATA.stats.occ)} records · ${fmt(DATA.stats.species)} species`;
  drawDock(total, shown);
}

/** One filled rectangle per grid cell. The data IS a grid, so this draws
 *  exactly what we hold — no interpolation, and no overlap to manage. */
function drawHeatCells(cells, counts){
  const half = viewCell / 2;
  const breaks = state.breaks;
  cells.forEach((c, i) => {
    const n = counts[i];
    if (!n) return;
    const rect = L.rectangle(
      [[c.y - half, c.x - half], [c.y + half, c.x + half]], {
        stroke: false, fillColor: heatColour(n, breaks), fillOpacity: .78,
        className: 'heatcell',
      });
    rect.bindTooltip(`<b>${fmt(n)}</b> occurrence record${n === 1 ? '' : 's'}<br>
      <span class="dim">${viewCell.toFixed(2)}° cell · click to zoom in</span>`,
      {direction:'top', sticky:true, className:'clutip'});
    rect.on('click', () => map.setView([c.y, c.x],
      Math.min(17, map.getZoom() + 2), {animate:false}));
    clusterLayer.addLayer(rect);
  });
}

function drawBubbles(cells, counts, zoom){
  const nmax = Math.max(1, ...counts);
  cells.forEach((c, i) => {
    const n = counts[i];
    if (!n) return;
    const r = clusterRadius(n, nmax, zoom, viewCell);
    const label = n > 999 ? (n / 1000).toFixed(n > 9999 ? 0 : 1) + 'k' : n;
    const m = L.marker([c.y, c.x], {
      icon: L.divIcon({
        className: 'clui',
        // size the type to the label so "25.0k" does not spill out of a disc
        // sized for "42" (bold digits run ~0.62em wide)
        html: `<span class="clud" style="width:${r*2}px;height:${r*2}px;
                 font-size:${Math.max(7.5, Math.min(r * 0.8,
                   (r * 1.8) / (String(label).length * 0.62))).toFixed(1)}px">${label}</span>`,
        iconSize: [r*2, r*2], iconAnchor: [r, r],
      }),
      keyboard: false,
    });
    m.bindTooltip(`<b>${fmt(n)}</b> occurrence record${n === 1 ? '' : 's'}<br>
      <span class="dim">click to zoom in</span>`,
      {direction:'top', offset:[0,-r], className:'clutip'});
    m.on('click', () => map.setView([c.y, c.x], Math.min(17, map.getZoom() + 2), {animate:false}));
    clusterLayer.addLayer(m);
  });
}

function drawSpeciesMap(){
  clusterLayer.clearLayers();
  pointLayer.clearLayers();
  const pts = live ? live.points : [];
  // Records at the SAME coordinate stack into one dot — a species known from a
  // single locality can have many records at one point (Cyrtodactylus
  // bhupathyi: 6 records, 1 location). Group coincident records so the map
  // shows one marker carrying the count, rather than looking like a single
  // record when there are several.
  const groups = new Map();
  pts.forEach(rec => {
    const key = rec.lat.toFixed(4) + ',' + rec.lon.toFixed(4);
    let g = groups.get(key);
    if (!g){ g = {lat: rec.lat, lon: rec.lon, recs: []}; groups.set(key, g); }
    g.recs.push(rec);
  });
  window.__locations = groups.size;
  groups.forEach(g => {
    const n = g.recs.length;
    const marine = g.recs[0].src === 'OBIS';
    const r = n > 1 ? Math.min(11, 5 + Math.sqrt(n) * 1.4) : 5;
    const c = L.circleMarker([g.lat, g.lon], {
      radius: r, weight: 1.2, color: '#fff', opacity: .85,
      fillColor: marine ? '#2563EB' : '#EF4444', fillOpacity: .9, className: 'occpt',
    });
    if (n > 1){
      c.bindTooltip(`<b>${fmt(n)}</b> records at this location`,
        {direction: 'top', className: 'clutip'});
    }
    // click shows the first record, noting how many share the spot
    c.on('click', ev => { L.DomEvent.stopPropagation(ev);
      showRecord(g.recs[0], ev.originalEvent, n); });
    pointLayer.addLayer(c);
  });
  $('#r-occ').textContent = fmt((live && live.total) ?? picked.n);
  $('#r-sp').textContent = '1';
  $('#r-cl').textContent = '—';
  $('#foot').textContent = `${picked.sci} · ${fmt(picked.n)} records`;
  drawDock(picked.n, 0);
}

/* ── camera ───────────────────────────────────────────── */
/** Frame a lat/lon bounding box. Leaflet owns the projection and the
 *  animation; we only decide what should be visible. */
/** Padding that reflects what is actually VISIBLE. The filters panel, the
 *  region panel and the dock all overlay the map rather than shrinking it, so
 *  symmetric padding centres a region behind them — the user saw a selected
 *  country sitting half under the dock. */
function viewPadding(){
  const w = map.getSize().x, h = map.getSize().y;
  let left  = $('#panel').classList.contains('closed') ? 14 : $('#panel').offsetWidth + 18;
  let right = $('#rgnpanel').classList.contains('closed') ? 14 : $('#rgnpanel').offsetWidth + 18;
  const rep = $('#report').classList.contains('on') ? $('#report').offsetWidth : 0;
  right += rep;
  let bottom = $('#dock').classList.contains('closed') ? 52 : $('#dock').offsetHeight + 18;
  // on a narrow window the panels can cover most of the map; refuse to pad
  // past what is left or Leaflet has nothing to fit into
  if (left + right > w * 0.75){ left = right = 14; }
  // an expanded dock can claim ~78% of the height; clamp rather than discard,
  // so the region still lands in the strip above it instead of behind it
  if (bottom > h * 0.55) bottom = Math.round(h * 0.55);
  return {paddingTopLeft: L.point(left, 24), paddingBottomRight: L.point(right, bottom)};
}

function fitBounds(bounds, maxZoom = 12){
  if (!bounds || !bounds.isValid()) return;
  // animate:false is load-bearing. Leaflet's zoom animation is driven by
  // requestAnimationFrame; in a throttled or backgrounded tab it starts and
  // never finishes, so the camera silently never arrives at the region. User
  // -driven zoom (buttons, wheel) keeps its animation — only programmatic
  // framing is forced to apply immediately.
  map.fitBounds(bounds, {...viewPadding(), maxZoom, animate:false});
}

/** Frame every occurrence point of the selected species. Ranges vary from a
 *  single hill to the whole subcontinent, so this is fitted, not fixed. */
function fitToPoints(pts){
  if (!pts || !pts.length) return;      // nothing to frame: leave the camera
  fitBounds(L.latLngBounds(pts.map(p => [p.lat, p.lon])));
}

// zoom changes which cluster grid is appropriate; only redraw when it flips
map.on('zoomend', () => {
  hideTip();
  if (picked) return;
  const lv = levelFor(map.getZoom());
  const flipped = lv !== state.z;
  state.z = lv;
  // bubble radius and heat class breaks both depend on zoom, so the map is
  // redrawn on every zoom; a full render() (which rebuilds the panel) is only
  // needed when the grid level itself changes
  if (flipped) return render();
  drawMap(); drawRegion(); drawLegend();
});
map.on('movestart', hideTip);
map.on('click', () => $('#rc2').classList.remove('on'));

const setZoom = dir => dir > 0 ? map.zoomIn() : map.zoomOut();

/* ── tooltip + single record ──────────────────────────── */
const tip = $('#tip');
// Leaflet's closeTooltip() calls .close() on its argument, so it must never be
// called bare; close through the layers that own the tooltips instead.
function hideTip(){
  tip.style.opacity = 0;
  clusterLayer.eachLayer(l => l.closeTooltip && l.closeTooltip());
}

function showRecord(rec, ev, coincident){
  const el = $('#rc2');
  const basis = (rec.basis || '').replace(/_/g,' ').toLowerCase();
  const rows = [
    ['Date', rec.date || 'not recorded'],
    ['Basis', basis ? basis[0].toUpperCase() + basis.slice(1) : '—'],
    ['Recorded by', rec.who || 'not recorded'],
    ['Dataset', rec.ds || '—'],
    ['Country', rec.country || '—'],
    ['Coordinate precision', rec.unc != null ? `± ${fmt(rec.unc)} m` : 'not stated'],
    ['Source', rec.src || 'GBIF'],
  ];
  el.innerHTML = `<button class="x" aria-label="Close">×</button>
    <h5>Occurrence record</h5>
    <div class="sci">${picked.sci}</div>
    ${coincident > 1 ? `<div class="coincident">${fmt(coincident)} records share this exact coordinate — showing the first.</div>` : ''}
    <dl>${rows.map(([k,v]) => `<dt>${k}</dt><dd>${v}</dd>`).join('')}</dl>
    <div class="gk">${rec.src === 'OBIS' ? 'OBIS' : 'GBIF'} record ${rec.key || '—'}
      · fetched live from ${rec.src === 'OBIS' ? 'OBIS (marine)' : 'GBIF'}</div>`;
  el.classList.add('on');
  el.querySelector('.x').onclick = () => el.classList.remove('on');
  const st = $('#stage').getBoundingClientRect();
  const w = 268, h = el.offsetHeight;
  let l = ev.clientX - st.left + 14;
  if (l + w > st.width - 8) l = ev.clientX - st.left - w - 14;
  el.style.left = Math.max(8, l) + 'px';
  el.style.top = Math.max(8, Math.min(ev.clientY - st.top - h/2, st.height - h - 8)) + 'px';
}

/* ── dock ─────────────────────────────────────────────── */
function drawDock(totalRecords, clusterCount){
  const box = $('#cards'); box.innerHTML = '';
  if (!picked){
    $('#expand').hidden = true;
    $('#dock').classList.remove('full');
    $('#dockttl').textContent = 'Overview';
    const scope = (state.grp.size || state.iucn.size || state.q) ? 'Filtered selection' : 'All India';
    box.insertAdjacentHTML('beforeend', `<div class="ic sum"><h4>${scope}</h4>
      <div class="big">${fmt(totalRecords)}</div><div class="sub">occurrence records</div>
      <div class="sub" style="margin-top:6px">across <b>${fmt(clusterCount)}</b> clusters</div></div>`);
    const st = DATA.facets.iucn.filter(f => !state.iucn.size || state.iucn.has(f.k));
    const tot = st.reduce((a,f) => a + f.n, 0) || 1;
    box.insertAdjacentHTML('beforeend', `<div class="ic dist"><h4>Conservation status</h4>
      <div class="bar">${st.map(f => `<span style="width:${(f.n/tot*100).toFixed(1)}%;background:var(${IUC[f.k]})"></span>`).join('')}</div>
      <div class="dl">${st.map(f => `<div><i style="background:var(${IUC[f.k]})"></i>${f.label}<b>${fmt(f.n)}</b></div>`).join('')}</div></div>`);
    box.insertAdjacentHTML('beforeend',
      `<div class="hollow"><span style="font-size:16px;color:var(--accent)">←</span>
        Select a species to load its photographs and occurrence records.</div>`);
    $('#dockhint').textContent = `${fmt(INDEX.filter(matches).length)} species available`;
    return;
  }

  $('#expand').hidden = false;
  $('#expand').textContent = full ? 'Collapse ▾' : 'Full record ▴';
  $('#dockttl').textContent = 'Species record';
  const n = live ? live.points.length : 0;
  $('#dockhint').innerHTML = live
    ? `${fmt(n)} of ${fmt(live.total ?? picked.n)} records plotted${
        (window.__locations && window.__locations < n) ? ` · ${fmt(window.__locations)} location${window.__locations === 1 ? '' : 's'}` : ''}`
      + (live.obis ? ` · <b>+${fmt(live.obis)}</b> from OBIS` : '')
      + (live.errors.length
        ? ` · <span class="warn">${live.errors.join(', ')} unavailable</span>` : '')
    : '<span class="dim">fetching photographs and records…</span>';

  if (full) return drawRecord();

  const c = `var(${IUC[picked.iucn]})`;
  const photo = live && live.photos[0];
  box.insertAdjacentHTML('beforeend', `<div class="ic idhero" style="--c:${c}">
    ${photo ? `<img src="${photo.url}" alt="${picked.sci}">`
            : `<span class="phbox${live ? ' none' : ' load'}"></span>`}
    <div><div class="nm">${picked.sci}</div>
      <div class="cm">${picked.com || 'No common name'}</div>
      <div class="ln">${picked.fam} · ${picked.grp}</div>
      <span class="st">${IUNAME[picked.iucn]}</span></div></div>`);

  const d = detail;
  box.insertAdjacentHTML('beforeend', `<div class="ic kv">
    <div><dt>Occurrence records</dt><dd>${fmt((live && live.total) ?? picked.n)}</dd><div class="src">GBIF, live</div></div>
    <div><dt>Population trend</dt><dd>${(d && d.trend) || '—'}</dd><div class="src">IUCN Red List</div></div>
    <div><dt>Region</dt><dd style="font-size:11px">${(d && d.realm) || '—'}</dd><div class="src">IUCN realms</div></div>
    <div><dt>Family</dt><dd style="font-size:11.5px">${picked.fam}</dd><div class="src">IUCN taxonomy</div></div></div>`);

  if (d && d.hab.length){
    box.insertAdjacentHTML('beforeend',
      `<div class="ic"><h4>Habitat</h4><div class="hbs">${d.hab.slice(0,6).map(h => `<span>${h}</span>`).join('')}</div></div>`);
  }
  box.insertAdjacentHTML('beforeend', '<div class="srcnote">IUCN Red List · GBIF · iNaturalist</div>');
  const clr = document.createElement('div');
  clr.className = 'recbtns';
  clr.innerHTML = `<button class="rgnpdf recexport">Export PDF</button>
    <button class="link">Clear selection ×</button>`;
  clr.querySelector('.recexport').onclick = e => makeSpeciesReport(picked, e.currentTarget);
  clr.querySelector('.link').onclick = () => selectSpecies(picked);
  box.appendChild(clr);
}


/** Genetic-resource availability from NCBI (precomputed, public domain).
 *  Not a genomics view — a research-completeness signal with live deep links.
 *  Absent for a species the NCBI pass has not yet covered. */
function geneticsCard(sp){
  const g = sp.gen_;
  if (!g) return '';
  const barcode = g.c > 0
    ? `<b>Yes</b> · ${fmt(g.c)} COI` : 'None on record';
  const genome = g.g > 0 ? `<b>${fmt(g.g)}</b>` : 'None';
  const seq = g.s > 0
    ? `<a class="link" href="${API.ncbiSeq(sp.sci)}" target="_blank" rel="noopener">${fmt(g.s)} on GenBank ↗</a>`
    : 'No sequences on record';
  return `<div class="secttl">Genetic resources</div>
    <dl class="qf">
      <div><dt>GenBank sequences</dt><dd style="font-size:12px">${seq}</dd><div class="src">NCBI, public domain</div></div>
      <div><dt>DNA barcode (COI)</dt><dd style="font-size:12px">${barcode}</dd><div class="src">for molecular ID</div></div>
      <div><dt>Sequenced genome</dt><dd style="font-size:12px">${genome}</dd>
        <div class="src">${g.g > 0 ? `<a class="link" href="${API.ncbiGenome(sp.sci)}" target="_blank" rel="noopener">NCBI Assembly ↗</a>` : 'NCBI Assembly'}</div></div>
      <div><dt>Taxonomy</dt><dd style="font-size:12px"><a class="link" href="${API.ncbiTax(sp.sci)}" target="_blank" rel="noopener">NCBI ↗</a></dd><div class="src">reference record</div></div>
    </dl>`;
}

function drawRecord(){
  const sp = picked, d = detail, c = `var(${IUC[sp.iucn]})`;
  const photos = live ? live.photos : [];
  const wrap = document.createElement('div');
  wrap.className = 'rec';
  wrap.innerHTML = `
    <div>
      <div class="gal">
        ${photos.length
          ? `<img class="hero" id="gh" data-i="0" src="${photos[0].url}" alt="${sp.sci}">
             ${photos.slice(1).map((p, i) =>
                `<img class="th" data-i="${i+1}" src="${p.url}" alt="">`).join('')}`
          : `<div class="phbox hero ${live ? 'none' : 'load'}"></div>`}
      </div>
      <div class="credit" id="cred">${photos[0] ? photos[0].credit : (live ? 'No photograph available.' : 'Loading photographs…')}</div>
      <div class="secttl">Habitat</div>
      <div class="chips">${((d && d.hab.length) ? d.hab : ['—']).map(h => `<span>${h}</span>`).join('')}</div>
    </div>
    <div>
      <div class="rhead" style="--c:${c}">
        <div class="nm">${sp.sci}</div>
        <div class="cm">${sp.com || 'No common name'}</div>
        <div class="ln">${(d && d.lineage.join(' · ')) || sp.fam}</div>
        <div class="badges"><span class="bdg" style="--c:${c}">${IUNAME[sp.iucn]}</span>
          ${d && d.venom ? `<span class="venom">⚠ Venomous — ${d.venom.l}</span>` : ''}</div>
        <button class="rgnpdf recexport-full">Export species PDF ↧</button>
      </div>
      <div class="secttl" style="margin-top:16px">Nomenclature</div>
      <div class="nom">
        <div class="n1">${sp.sci}<small>IUCN Red List${!d || !d.inatName || d.inatName === sp.sci ? ' · iNaturalist — names agree' : ''}</small></div>
        ${d && d.inatName && d.inatName !== sp.sci ? `<div class="n2">${d.inatName}<small>iNaturalist</small></div>` : ''}
      </div>
      <dl class="qf">
        <div><dt>Occurrence records</dt><dd>${fmt(sp.n)}</dd><div class="src">GBIF</div></div>
        <div><dt>Assessed</dt><dd>${(d && d.yr) || '—'}</dd><div class="src">IUCN</div></div>
        <div><dt>Population trend</dt><dd>${(d && d.trend) || '—'}</dd><div class="src">IUCN</div></div>
        <div><dt>Region</dt><dd style="font-size:11.5px">${(d && d.realm) || '—'}</dd><div class="src">IUCN realms</div></div>
      </dl>
      ${d && d.venom ? `<div class="secttl">Venom</div><div class="ai">
        <article style="border-left-color:#F0554A"><h5 style="color:#FF8A80">${d.venom.l}</h5>
        <p>${d.venom.s || ''} — recorded with <b>${d.venom.c}</b> confidence.</p></article></div>` : ''}
      ${geneticsCard(picked)}
      <div class="secttl">Field notes</div>
      <div class="aiwarn">✦ AI-generated · not expert-verified</div>
      <div class="seg" role="tablist">
        ${SEGS.map(([name, keys], i) => {
          const k = d ? keys.filter(x => d.ai[x]).length : 0;
          return `<button role="tab" data-seg="${i}" aria-selected="${i===seg}"
            ${k ? '' : 'disabled style="opacity:.4"'}>${name}<span class="c">${k}</span></button>`;
        }).join('')}
      </div>
      <div class="ai" id="ai"></div>
      <div class="segnote">Range is shown on the map — occurrence points are fetched live from GBIF.</div>
      <div class="secttl">Provenance</div>
      <p class="provp">Status, assessment, trend, region and habitat from the <b>IUCN Red List</b>.
        Occurrence points fetched live from <b>GBIF</b>. Photographs fetched live from
        <b>iNaturalist</b>, each carrying its own contributor credit and licence.
        Genetic-resource counts from <b>NCBI</b> (public domain), linking to the live database.
        Field notes are machine-generated and have not been reviewed by a specialist.</p>
    </div>`;
  $('#cards').appendChild(wrap);

  wrap.querySelector('.recexport-full')
     ?.addEventListener('click', e => makeSpeciesReport(picked, e.currentTarget));

  // Respect each photo's orientation: size the hero frame to the image's own
  // aspect ratio (clamped) so object-fit:cover shows the whole photo instead of
  // hard-cropping a portrait into a square.
  const fitHero = () => { const h = wrap.querySelector('#gh');
    if (h && h.naturalWidth) h.style.aspectRatio = Math.max(0.62, Math.min(1.85, h.naturalWidth / h.naturalHeight)); };

  function paintSeg(){
    const keys = d ? SEGS[seg][1].filter(k => d.ai[k]) : [];
    wrap.querySelector('#ai').innerHTML = keys.length
      ? keys.map(k => `<article><h5>${AILAB[k]}</h5><p>${md(d.ai[k])}</p></article>`).join('')
      : `<article><p class="dim">${d ? `No ${SEGS[seg][0].toLowerCase()} notes for this species yet.` : 'Loading…'}</p></article>`;
    wrap.querySelectorAll('.seg button').forEach(b =>
      b.setAttribute('aria-selected', Number(b.dataset.seg) === seg));
  }
  wrap.querySelectorAll('.seg button').forEach(b => {
    b.onclick = () => { seg = Number(b.dataset.seg); paintSeg(); };
  });
  paintSeg();

  // A thumbnail promotes itself into the hero slot; only the hero opens the
  // full-screen viewer. Clicking a 60px thumbnail straight to full screen was
  // skipping the step where you actually look at the photograph in place.
  wrap.querySelectorAll('.gal .th').forEach(im => {
    im.onclick = () => {
      const hero = wrap.querySelector('#gh');
      const hi = Number(hero.dataset.i), ti = Number(im.dataset.i);
      hero.src = photos[ti].url; hero.dataset.i = ti;
      im.src = photos[hi].url;   im.dataset.i = hi;
      fitHero();
      const p = photos[ti];
      const c = wrap.querySelector('#cred');
      if (c) c.textContent = [p.credit, p.licence ? p.licence.toUpperCase() : '']
        .filter(Boolean).join(' · ');
    };
  });
  const hero = wrap.querySelector('#gh');
  if (hero){
    hero.onclick = () => openLightbox(photos, Number(hero.dataset.i), sp.sci);
    hero.addEventListener('load', fitHero); fitHero();
  }
}

/* ── full-screen photo viewer ─────────────────────────── */
let lb = null;   // {photos, i, sci}

function openLightbox(photos, i, sci){
  if (!photos || !photos.length) return;
  lb = {photos, i, sci};
  const el = $('#lb');
  el.hidden = false;
  el.innerHTML = `
    <button class="lbx" aria-label="Close photograph">✕</button>
    <button class="lbnav lbprev" aria-label="Previous photograph">‹</button>
    <figure class="lbfig">
      <img id="lbimg" alt="">
      <figcaption>
        <div class="lbname">${sci}</div>
        <div class="lbcred" id="lbcred"></div>
        <div class="lbcount" id="lbcount"></div>
      </figcaption>
    </figure>
    <button class="lbnav lbnext" aria-label="Next photograph">›</button>`;
  el.querySelector('.lbx').onclick = closeLightbox;
  el.querySelector('.lbprev').onclick = e => { e.stopPropagation(); step(-1); };
  el.querySelector('.lbnext').onclick = e => { e.stopPropagation(); step(1); };
  // clicking the backdrop closes; clicking the photo itself must not
  el.onclick = e => { if (e.target === el) closeLightbox(); };
  el.querySelector('.lbfig').onclick = e => e.stopPropagation();
  document.body.classList.add('lbopen');
  paintLightbox();
  el.querySelector('.lbx').focus();
}

function paintLightbox(){
  if (!lb) return;
  const p = lb.photos[lb.i];
  const img = $('#lbimg');
  img.src = p.url;
  img.alt = `${lb.sci} — photograph ${lb.i + 1} of ${lb.photos.length}`;
  // credit and licence travel with each photograph, never the set
  $('#lbcred').textContent = [p.credit, p.licence ? p.licence.toUpperCase() : '']
    .filter(Boolean).join(' · ') || 'Credit unavailable';
  $('#lbcount').textContent = `${lb.i + 1} / ${lb.photos.length}`;
  const one = lb.photos.length < 2;
  $('#lb').querySelectorAll('.lbnav').forEach(b => b.hidden = one);
}

function step(d){
  if (!lb) return;
  lb.i = (lb.i + d + lb.photos.length) % lb.photos.length;   // wraps both ways
  paintLightbox();
}

function closeLightbox(){
  lb = null;
  const el = $('#lb');
  el.hidden = true; el.innerHTML = '';
  document.body.classList.remove('lbopen');
}

document.addEventListener('keydown', e => {
  if (!lb) return;
  if (e.key === 'Escape') closeLightbox();
  else if (e.key === 'ArrowRight') step(1);
  else if (e.key === 'ArrowLeft') step(-1);
});

/* ── legend, chrome ───────────────────────────────────── */
function drawLegend(){
  const el = $('#legend');
  if (picked){
    const hasRange = picked.rng;
    const nObis = (live && live.obis) || 0;
    el.innerHTML = `<div><i style="width:9px;height:9px;background:var(--occ)"></i> Occurrence record</div>
      ${nObis ? '<div><i style="width:9px;height:9px;background:#2563EB"></i> OBIS marine record</div>' : ''}
      ${hasRange ? '<div><i style="width:11px;height:9px;border-radius:2px;background:#38A169;opacity:.55"></i> IUCN range</div>' : ''}
      <div class="dim" style="font-size:10px">${(live && !live.points.length && hasRange)
        ? 'No georeferenced records — range shown' : 'click a point for its details'}</div>`;
    return;
  }
  if (state.view === 'heat'){
    const b = state.breaks || [];
    if (!b.length){ el.innerHTML = '<div class="dim">No records in view.</div>'; return; }
    // label each class by the range it actually covers, not a round number
    let lo = 1;
    el.innerHTML = `<div class="legttl">Occurrence records per ${cellDeg(state.z)}° cell</div>
      <div class="ramp">${b.map((hi, i) => {
        const row = `<div><i style="background:${HEAT[HEAT.length - b.length + i]}"></i>` +
          `<span>${lo === hi ? fmt(hi) : fmt(lo) + '–' + fmt(hi)}</span></div>`;
        lo = hi + 1;
        return row;
      }).join('')}</div>`;
    return;
  }
  el.innerHTML = `<div><i style="width:8px;height:8px"></i> &lt; 100 records</div>
     <div><i style="width:13px;height:13px"></i> 100 – 1,000</div>
     <div><i style="width:19px;height:19px"></i> &gt; 1,000</div>`;
}
function fitControls(){
  const d = $('#dock');
  document.documentElement.style.setProperty('--dockh',
    (d.classList.contains('closed') ? 35 : d.offsetHeight) + 'px');
  // centre the busy indicator in the space actually left by the panels, not
  // in the map container they sit on top of
  // Position every edge tab from MEASURED panel geometry rather than sibling
  // selectors: the dock tab sits before .dock in the DOM, so `.dock.closed ~`
  // never matched it, and the filters tab silently kept its open offset.
  const pl = $('#panel').classList.contains('closed') ? 0 : $('#panel').offsetWidth;
  const pr = $('#rgnpanel').classList.contains('closed') ? 0 : $('#rgnpanel').offsetWidth;

  const closed = d.classList.contains('closed');
  const t = $('#dockhandle');
  if (t){
    // Positioned from JS, not CSS. The cascade resolved `bottom:var(--dockh)`
    // to its fallback even with --dockh set, and chasing that further was not
    // worth it — an inline value is unambiguous and always correct.
    t.style.bottom = (closed ? 35 : d.offsetHeight) + 'px';
    t.style.left = (pl + (map.getSize().x - pl - pr) / 2) + 'px';
    t.setAttribute('aria-expanded', !closed);
    $('#dockhandleIcon').textContent = closed ? '⌃' : '⌄';
  }
  const ft = $('#handle');
  if (ft) ft.style.left = pl + 'px';
  const gt = $('#rgnhandle');
  if (gt) gt.style.right = pr + 'px';
  const p = viewPadding();
  document.documentElement.style.setProperty('--busyshift',
    ((p.paddingTopLeft.x - p.paddingBottomRight.x) / 2).toFixed(0) + 'px');
}

function render(){
  if (!DATA) return;
  hideTip();
  $('#rc2').classList.remove('on');
  // buildPanel() recreates #pbody, so clicking a tree node or a filter would
  // otherwise jump the panel back to the top. Preserve the scroll positions of
  // both the panel and the inner tree across the rebuild.
  const pb = $('#pbody');
  const pbTop = pb ? pb.scrollTop : 0;
  const trOld = pb && pb.querySelector('.tree');
  const trTop = trOld ? trOld.scrollTop : 0;
  buildPanel(); drawMap(); drawRegion(); drawLegend();
  if (typeof paintRegionPanel === 'function' && rIndex) paintRegionPanel();
  if (pb){
    pb.scrollTop = pbTop;
    const trNew = pb.querySelector('.tree');
    if (trNew) trNew.scrollTop = trTop;
  }
  fitControls();
}

$('#q').addEventListener('input', e => { state.q = e.target.value.trim(); state.shown = 60; render(); });
$('#zin').onclick = () => setZoom(1);
$('#zout').onclick = () => setZoom(-1);
$('#reset').onclick = () => {
  state.grp.clear(); state.iucn.clear(); state.q = ''; $('#q').value = '';
  state.shown = 60;
  map.fitBounds([[P.minLat, P.minLon], [P.maxLat, P.maxLon]],
    {...viewPadding(), animate:false});
  picked = detail = live = null; full = false;
  $('#dock').classList.remove('full');
  render();
};
$('#handle').onclick = () => {
  const closed = $('#panel').classList.toggle('closed');
  $('#handle').setAttribute('aria-expanded', !closed);
  $('#handleIcon').textContent = closed ? '›' : '‹';
  fitControls();
};

// the dock gets the same edge-tab affordance as the side panels
$('#dockhandle').onclick = () => {
  const closed = $('#dock').classList.toggle('closed');
  $('#dockhandle').setAttribute('aria-expanded', !closed);
  $('#dockhandleIcon').textContent = closed ? '⌃' : '⌄';
  $('#dockbar').setAttribute('aria-expanded', !closed);
  fitControls();
};
$('#expand').onclick = e => {
  e.stopPropagation();
  full = !full;
  $('#dock').classList.toggle('full', full);
  if (full) $('#dock').classList.remove('closed');
  render();
};
$('#dockbar').onclick = () => {
  const c = $('#dock').classList.toggle('closed');
  $('#dockbar').setAttribute('aria-expanded', !c);
  fitControls();
};
window.addEventListener('resize', fitControls);

$('#rgnhandle').onclick = () => {
  const closed = $('#rgnpanel').classList.toggle('closed');
  document.body.classList.toggle('rgnclosed', closed);
  $('#rgnhandle').setAttribute('aria-expanded', !closed);
  $('#rgnhandleIcon').textContent = closed ? '‹' : '›';
  fitControls(); map.invalidateSize();
};
$('#baseSel').onchange = e => setBasemap(e.target.value);

document.querySelectorAll('#viewToggle .chip').forEach(b => {
  b.onclick = () => {
    state.view = b.dataset.view;
    // the pressed state is what tells the user which view is live — the chip
    // CSS keys on aria-pressed, and nothing was updating it
    document.querySelectorAll('#viewToggle .chip').forEach(o =>
      o.setAttribute('aria-pressed', o === b));
    // the two views have different readability floors, so the appropriate
    // grid level changes with them
    state.z = levelFor(map.getZoom());
    render();
  };
});

/* ── busy indicator ───────────────────────────────────────
 * Photographs and occurrence points are fetched live and take a few seconds,
 * during which the map is simply empty. Say so rather than looking broken. */
let busyDepth = 0;
function setBusy(on, label){
  busyDepth = Math.max(0, busyDepth + (on ? 1 : -1));
  const el = $('#busy');
  el.hidden = busyDepth === 0;
  if (busyDepth && label) el.querySelector('.busylbl').textContent = label;
}
